In [12]:
#Import libraries for operations and dataframe
import numpy as np
import pandas as pd
#Import the Libraries for visualision
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
#Import dataset 
dataset = pd.read_csv('heart.csv')

In [14]:
#Check data set quick view
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

### We have a mix of binary and numerical features

In [15]:
#check for data types and empty cells
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


### there are no missing values

In [16]:
#Check stats of the dataset
dataset.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

##### There are no weird outliers, things look intact

In [17]:
#Check for correlation of data for future analysis
dataset.corr()

age       sex        cp  trestbps      chol       fbs  \
age       1.000000 -0.098447 -0.068653  0.279351  0.213678  0.121308   
sex      -0.098447  1.000000 -0.049353 -0.056769 -0.197912  0.045032   
cp       -0.068653 -0.049353  1.000000  0.047608 -0.076904  0.094444   
trestbps  0.279351 -0.056769  0.047608  1.000000  0.123174  0.177531   
chol      0.213678 -0.197912 -0.076904  0.123174  1.000000  0.013294   
fbs       0.121308  0.045032  0.094444  0.177531  0.013294  1.000000   
restecg  -0.116211 -0.058196  0.044421 -0.114103 -0.151040 -0.084189   
thalach  -0.398522 -0.044020  0.295762 -0.046698 -0.009940 -0.008567   
exang     0.096801  0.141664 -0.394280  0.067616  0.067023  0.025665   
oldpeak   0.210013  0.096093 -0.149230  0.193216  0.053952  0.005747   
slope    -0.168814 -0.030711  0.119717 -0.121475 -0.004038 -0.059894   
ca        0.276326  0.118261 -0.181053  0.101389  0.070511  0.137979   
thal      0.068001  0.210041 -0.161736  0.062210  0.098803 -0.032019   
target   -0.225439 -0.280937  0.433798 -0.144931 -0.085239 -0.028046   

           restecg   thalach     exang   oldpeak     slope        ca  \
age      -0.116211 -0.398522  0.096801  0.210013 -0.168814  0.276326   
sex      -0.058196 -0.044020  0.141664  0.096093 -0.030711  0.118261   
cp        0.044421  0.295762 -0.394280 -0.149230  0.119717 -0.181053   
trestbps -0.114103 -0.046698  0.067616  0.193216 -0.121475  0.101389   
chol     -0.151040 -0.009940  0.067023  0.053952 -0.004038  0.070511   
fbs      -0.084189 -0.008567  0.025665  0.005747 -0.059894  0.137979   
restecg   1.000000  0.044123 -0.070733 -0.058770  0.093045 -0.072042   
thalach   0.044123  1.000000 -0.378812 -0.344187  0.386784 -0.213177   
exang    -0.070733 -0.378812  1.000000  0.288223 -0.257748  0.115739   
oldpeak  -0.058770 -0.344187  0.288223  1.000000 -0.577537  0.222682   
slope     0.093045  0.386784 -0.257748 -0.577537  1.000000 -0.080155   
ca       -0.072042 -0.213177  0.115739  0.222682 -0.080155  1.000000   
thal     -0.011981 -0.096439  0.206754  0.210244 -0.104764  0.151832   
target    0.137230  0.421741 -0.436757 -0.430696  0.345877 -0.391724   

              thal    target  
age       0.068001 -0.225439  
sex       0.210041 -0.280937  
cp       -0.161736  0.433798  
trestbps  0.062210 -0.144931  
chol      0.098803 -0.085239  
fbs      -0.032019 -0.028046  
restecg  -0.011981  0.137230  
thalach  -0.096439  0.421741  
exang     0.206754 -0.436757  
oldpeak   0.210244 -0.430696  
slope    -0.104764  0.345877  
ca        0.151832 -0.391724  
thal      1.000000 -0.344029  
target   -0.344029  1.000000

##### based on personal judgement we will choose correlation of above or near 25%

In [22]:
#Choose arrays for regression analysis
X = dataset.iloc[:, [0, 1,2,7,8,9,10,11,12]].values
y = dataset.iloc[:, -1].values

In [23]:
pd.DataFrame(X)

0    1    2      3    4    5    6    7    8
0    63.0  1.0  3.0  150.0  0.0  2.3  0.0  0.0  1.0
1    37.0  1.0  2.0  187.0  0.0  3.5  0.0  0.0  2.0
2    41.0  0.0  1.0  172.0  0.0  1.4  2.0  0.0  2.0
3    56.0  1.0  1.0  178.0  0.0  0.8  2.0  0.0  2.0
4    57.0  0.0  0.0  163.0  1.0  0.6  2.0  0.0  2.0
..    ...  ...  ...    ...  ...  ...  ...  ...  ...
298  57.0  0.0  0.0  123.0  1.0  0.2  1.0  0.0  3.0
299  45.0  1.0  3.0  132.0  0.0  1.2  1.0  0.0  3.0
300  68.0  1.0  0.0  141.0  0.0  3.4  1.0  2.0  3.0
301  57.0  1.0  0.0  115.0  1.0  1.2  1.0  1.0  3.0
302  57.0  0.0  1.0  174.0  0.0  0.0  1.0  1.0  2.0

[303 rows x 9 columns]

In [26]:
pd.DataFrame(y)

0
0    1
1    1
2    1
3    1
4    1
..  ..
298  0
299  0
300  0
301  0
302  0

[303 rows x 1 columns]

In [27]:
#since data exist is different formats 
#we need to find a common standard using standard scaler
from sklearn.preprocessing import StandardScaler
scale = StandardScaler()
X = scale.fit_transform(X)

In [28]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.952197  0.681005  1.973123  0.015443 -0.696631  1.087338 -2.274579   
1   -1.915313  0.681005  1.002577  1.633471 -0.696631  2.122573 -2.274579   
2   -1.474158 -1.468418  0.032031  0.977514 -0.696631  0.310912  0.976352   
3    0.180175  0.681005  0.032031  1.239897 -0.696631 -0.206705  0.976352   
4    0.290464 -1.468418 -0.938515  0.583939  1.435481 -0.379244  0.976352   
..        ...       ...       ...       ...       ...       ...       ...   
298  0.290464 -1.468418 -0.938515 -1.165281  1.435481 -0.724323 -0.649113   
299 -1.033002  0.681005  1.973123 -0.771706 -0.696631  0.138373 -0.649113   
300  1.503641  0.681005 -0.938515 -0.378132 -0.696631  2.036303 -0.649113   
301  0.290464  0.681005 -0.938515 -1.515125  1.435481  0.138373 -0.649113   
302  0.290464 -1.468418  0.032031  1.064975 -0.696631 -0.896862 -0.649113   

            7         8  
0   -0.714429 -2.148873  
1   -0.714429 -0.512922  
2   -0.714429 -0.512922  
3   -0.714429 -0.512922  
4   -0.714429 -0.512922  
..        ...       ...  
298 -0.714429  1.123029  
299 -0.714429  1.123029  
300  1.244593  1.123029  
301  0.265082  1.123029  
302  0.265082 -0.512922  

[303 rows x 9 columns]

In [29]:
# Splitting dataset into training and test arrays
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 41)



In [31]:
# Feature Scaling to avoid dicrepencies between inputted X values
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [32]:
#Confirm results
X_train, X_test

(array([[ 1.20382544, -1.49761715,  0.9743733 , ...,  0.93919819,
          0.23176179, -0.49979604],
        [-1.1432649 ,  0.66772739,  0.9743733 , ...,  0.93919819,
         -0.74249611, -0.49979604],
        [-1.70209593,  0.66772739,  0.9743733 , ...,  0.93919819,
         -0.74249611, -0.49979604],
        ...,
        [ 0.421462  , -1.49761715, -0.98299607, ..., -0.7264111 ,
         -0.74249611, -0.49979604],
        [ 0.30969579,  0.66772739, -0.98299607, ..., -0.7264111 ,
          0.23176179,  1.12097113],
        [-1.47856352,  0.66772739,  0.9743733 , ...,  0.93919819,
         -0.74249611, -0.49979604]]),
 array([[-1.1432649 ,  0.66772739, -0.98299607, -0.28596937,  1.46723474,
          1.56469404, -2.3920204 , -0.74249611, -2.12056321],
        [ 1.65089027,  0.66772739,  0.9743733 , -0.19860053, -0.6815542 ,
          0.86773932, -0.7264111 ,  2.18027759,  1.12097113],
        [-2.14916076,  0.66772739, -0.98299607, -0.89755125,  1.46723474,
          0.51926196, -0.72

In [33]:
# Fitting training set to Logistic Regression
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 42)
classifier.fit(X_train, y_train)

C:\Users\Symbios\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=42, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)


In [35]:
#print results
cm

array([[31,  7],
       [ 7, 31]], dtype=int64)

In [36]:
#Calculate Accuracy
from sklearn.metrics import classification_report
cr=classification_report(y_test, y_pred)
print(cr)

              precision    recall  f1-score   support

           0       0.82      0.82      0.82        38
           1       0.82      0.82      0.82        38

    accuracy                           0.82        76
   macro avg       0.82      0.82      0.82        76
weighted avg       0.82      0.82      0.82        76



### Model is 82% accurate